FROM node:20-alpine

WORKDIR /app

# ✅ Fix Prisma OpenSSL issue
RUN apk add --no-cache openssl

COPY package*.json ./
RUN npm install

COPY . .

# ✅ Generate Prisma for Linux (CRITICAL)
RUN npx prisma generate

RUN npm run build

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/main.js"]