'use client';

import { useState, useCallback } from 'react';
import Header from '@/components/Header/Header';
import ProductGrid from '@/components/Products/ProductGrid';
import ProductFormModal from '@/components/Forms/ProductFormModal';
import { Toaster } from 'react-hot-toast';

export default function Home() {
  const [isFormModalOpen, setIsFormModalOpen] = useState(false);
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  const handleProductCreated = useCallback(() => {
    setRefreshTrigger((prev) => prev + 1);
  }, []);

  return (
    <>
      <Toaster position="top-right" />

      <div className="min-h-screen bg-slate-50 text-slate-950">
        <Header onAddProduct={() => setIsFormModalOpen(true)} />

        <main className="container-custom py-12">
          <section className="grid gap-8 lg:grid-cols-[1.4fr_0.9fr] items-start">
            <div className="space-y-6">
              <div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-[0_25px_50px_-25px_rgba(15,23,42,0.12)]">
                <span className="inline-flex items-center rounded-full bg-amber-100 px-3 py-1 text-sm font-semibold text-amber-700">
                  FLASH SALE • Up to 60% off
                </span>
                <h1 className="mt-4 text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">
                  Shop the latest AI-powered product collection.
                </h1>
                <p className="mt-4 max-w-2xl leading-8 text-slate-600">
                  Discover premium products with rich descriptions generated by AI, styled with a modern store layout and intuitive product browsing experience.
                </p>
                {/* <div className="mt-6 flex flex-wrap gap-3">
                  <span className="category-pill">Fashion</span>
                  <span className="category-pill">Electronics</span>
                  <span className="category-pill">Home</span>
                  <span className="category-pill">Beauty</span>
                  <span className="category-pill">Sports</span>
                  <span className="category-pill">Accessories</span>
                </div> */}
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_20px_40px_-20px_rgba(15,23,42,0.08)]">
                  <p className="text-sm uppercase tracking-[0.3em] text-slate-400">Trending Now</p>
                  <h2 className="mt-3 text-2xl font-semibold text-slate-950">Curated Collections</h2>
                  <p className="mt-2 text-sm leading-6 text-slate-600">
                    Browse high-demand products with elegant design and intelligent content.
                  </p>
                </div>
                <div className="rounded-[2rem] border border-slate-200 bg-gradient-to-br from-sky-500/10 via-cyan-50 to-white p-6 shadow-[0_20px_40px_-20px_rgba(15,23,42,0.08)]">
                  <p className="text-sm uppercase tracking-[0.3em] text-sky-700">Trending Picks</p>
                  <h2 className="mt-3 text-2xl font-semibold text-slate-950">Best sellers and new arrivals</h2>
                  <p className="mt-2 text-sm leading-6 text-slate-600">
                    Quickly add products or explore the current collection in a refreshed layout.
                  </p>
                </div>
              </div>
            </div>

            <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-[0_25px_50px_-25px_rgba(15,23,42,0.12)]">
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="text-sm uppercase tracking-[0.3em] text-slate-400">Top picks</p>
                  <h2 className="mt-2 text-3xl font-semibold text-slate-950">ShopEasy Essentials</h2>
                </div>
                <div className="rounded-full bg-slate-950 px-4 py-2 text-sm text-white">Live</div>
              </div>
              <div className="mt-8 space-y-4">
                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
                  <p className="text-sm text-slate-500">Minimalist Leather Crossbody Bag</p>
                  <div className="mt-3 flex items-end justify-between gap-4">
                    <div>
                      <p className="text-2xl font-semibold text-slate-950">$89.99</p>
                      <p className="text-sm text-slate-500 line-through">$149.99</p>
                    </div>
                    <span className="badge-pill bg-rose-500 text-white">-40%</span>
                  </div>
                </div>
                <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5">
                  <p className="text-sm text-slate-500">Wireless Noise-Cancelling Earbuds Pro</p>
                  <div className="mt-3 flex items-end justify-between gap-4">
                    <div>
                      <p className="text-2xl font-semibold text-slate-950">$59.99</p>
                      <p className="text-sm text-slate-500 line-through">$129.99</p>
                    </div>
                    <span className="badge-pill bg-amber-500 text-slate-950">Flash</span>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="mt-12">
            <ProductGrid key={refreshTrigger} />
          </section>
        </main>

        <ProductFormModal
          isOpen={isFormModalOpen}
          onClose={() => setIsFormModalOpen(false)}
          onProductCreated={handleProductCreated}
        />

        <footer className="bg-slate-100 text-slate-600 p-6 mt-16 border-t border-slate-200">
          <div className="container-custom text-center">
            <p className="mb-2 text-sm">🛍️ AI Shop</p>
            <p className="text-xs text-slate-500">
              Built with modern web technologies for an engaging shopping experience.
            </p>
          </div>
        </footer>
      </div>
    </>
  );
}
